# Generated by Django 3.0.3 on 2020-06-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user1', max_length=30)),
                ('email', models.EmailField(default='a@gmail.com', max_length=254)),
                ('password', models.CharField(default='1234', max_length=15)),
            ],
        ),
    ]
