# Generated by Django 3.0.3 on 2020-06-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='1234', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='user1', max_length=30),
        ),
    ]
